import numpy as np
a=np.array([[1,2,3,4],[9,5,6,7]])
m=np.array([[6,7,3,4],[8,4,6,7]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a[0])
print(a[1][3])
print(a[0, 1:3])
print(a[:, 1])
print(a[:, 2:4])
print(a - 1)
print(a / 2)
b = np.array([10, 20, 30, 40])
print(a + b)#adds b for every row of a
print(np.sum(a))
print(np.mean(a))#mean → Where is the center? == average
print(np.min(a))
print(np.max(a))
print(np.std(a))#std  → How spread out are the values?
c = b.reshape(2, 2)
print(c)
d=a.flatten()
print(d)
e = np.zeros(5)
print(e)
f = np.zeros((2, 3))
print(f)
g = np.ones((2, 3))
print(g)
h=np.arange(1, 10)
print(h)
i=np.arange(2, 12, 3)
print(i)
j=np.linspace(0, 20, 5)
print(j)
k=np.random.rand(5)
print(k)
l=np.random.randint(10, 50, 6)
print(l)
n=m.reshape(4,2)
print(a * m)
print(a @ n)
print(np.sum(a, axis=0))#calculate for each column.
print(np.sum(a,axis=1))#calculate for each row.
result = np.where(a >= 5, "Pass", "Fail")
print(result)
print(np.unique(a))
o = np.concatenate((a, m))
print(o)